---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/ex_plotly/ex_plotly.htm
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/248238/articles/332668/master/file/figures/ex_plotly/ex_plotly.htm"
    folder_url: "/users/248238/articles/332668/master/folder/figures/ex_plotly"
